import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/shared/empty-state";
import { reportsApi } from "@/lib/api";
import { formatRelativeTime } from "@/lib/format";

export default async function ProjectReportsPage({
  params,
}: {
  params: Promise<{ projectId: string }>;
}) {
  const { projectId } = await params;
  const res = await reportsApi.fetchReports(projectId);
  if (!res.success) throw new Error(res.error.message);

  return (
    <Card>
      <CardContent>
        {res.data.length === 0 ? (
          <EmptyState title="No reports yet" description="Reports appear here once an audit finishes for this project." />
        ) : (
          <table className="w-full text-[13px]">
            <thead>
              <tr className="border-b border-border-default text-[11px] font-medium tracking-[0.04em] text-text-secondary uppercase">
                <th className="pb-2.5 text-left">Report Name</th>
                <th className="pb-2.5 text-left">Generated Date</th>
                <th className="pb-2.5 text-left">Generated By</th>
                <th className="pb-2.5 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {res.data.map((report) => (
                <tr key={report.id} className="border-b border-border-default last:border-0">
                  <td className="py-3 font-medium">{report.title}</td>
                  <td className="py-3 text-text-secondary">{formatRelativeTime(report.generatedAt)}</td>
                  <td className="py-3">{report.generatedBy}</td>
                  <td className="py-3">
                    <Link href="/reports" className="font-medium text-accent-default hover:underline">Open</Link>
                    <span className="mx-1.5 text-border-strong">&middot;</span>
                    <span className="font-medium text-accent-default">Download</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </CardContent>
    </Card>
  );
}
